#!/usr/bin/env bash
set -Eeuxo pipefail

[[ -f .vscode/settings.json ]] && <.vscode/settings.json jq -r '."workbench.colorCustomizations" | {
  active_fg: (."titleBar.activeForeground"[:7] // "NONE"),
  active_bg: (."titleBar.activeBackground"[:7] // "NONE"),
  inactive_fg: (."titleBar.inactiveBackground"[:7] // "NONE"),
  inactive_bg: (."titleBar.inactiveBackground"[:7] // "NONE"),
} | to_entries | map("\(.key)=\(.value)")[]' | xargs kitty @ set-tab-color


# current best option:
# - set $KITTY_ACTIVE_FG, $KITTY_ACTIVE_BG etc. in direnv based on the thing above
# if they are set and they weren't set last time or vice versa
#
# in precmd call set-tab-color
