[symgr]
git = "https://github.com/kbd/symgr.git"
# this command is equivalent to setting 'bin' to 'symgr',
# but this is bootstrapping the symlinking done for 'bin'
cmd = "ln -sf $(setup vendor)/symgr/symgr ~/bin/symgr"

[bak]
git = "https://github.com/kbd/bak.git"
bin = "bak"

[repo_status]
git = "https://github.com/kbd/repo_status.git"
cmd = "just build-release"
bin = "repo_status"

[prompt]
git = "https://github.com/kbd/prompt.git"
cmd = "just build-release"
bin = "prompt"

[zls]
git = "https://github.com/zigtools/zls.git"
tag = "0.15.0"
cmd = "zig build -Doptimize=ReleaseSafe"
bin = "zig-out/bin/zls"

[fzf-tab]
git = "https://github.com/Aloxaf/fzf-tab"
exe = "zsh"
cmd = """
dest=~/bin/shell/~3rdparty/fzf-tab.plugin.zsh
ln -sf ~/3rdparty/fzf-tab/fzf-tab.plugin.zsh $dest
zcompile $dest
"""

[tinkle]
url = "https://github.com/pqrs-org/Tinkle/releases/download/v2.4.0/Tinkle-2.4.0.dmg"
dmg = "/Volumes/Tinkle/Tinkle.app"

[zsh-bench]
git = "https://github.com/romkatv/zsh-bench.git"

[zsh-defer]
git = "https://github.com/romkatv/zsh-defer.git"
